# Generated by Django 5.2.5 on 2026-08-24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('accounts', '0005_user_avatar_seed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar_seed',
            field=models.CharField(default='young-man', max_length=20, verbose_name='default avatar'),
        ),
    ]
