# Generated by Django 6.1 on 2026-08-23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_task_weight'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='assignee',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name='assigned_tasks',
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
