# Generated by Django 5.2.5 on 2026-08-25

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('projects', '0011_projectfavorite'),
    ]

    operations = [
        migrations.AddField(
            model_name='timeentry',
            name='notes',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='timeentry',
            name='recorded_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=models.deletion.SET_NULL, related_name='recorded_time_entries', to=settings.AUTH_USER_MODEL),
        ),
    ]
