# Generated by Django 5.2.5 on 2026-08-25

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('projects', '0012_timeentry_notes_and_recorded_by'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='timeentry',
            name='unique_daily_project_time_entry',
        ),
    ]
