# Generated by Django 6.1 on 2026-08-25 14:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0016_worklog'),
    ]

    operations = [
        migrations.AddField(
            model_name='worklog',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='general_work_logs', to='projects.project'),
        ),
    ]
